name: Benchmark with ASV

on:
  push:
    branches: asvDevBranch
  pull_request:
    branches: asvDevBranch

jobs:
  asvContinuous:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 8
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Add conda to system path
      run: echo $CONDA/bin >> $GITHUB_PATH
    - name: Conda with Python Setup
      run: |
        conda init
        conda create -n "cloud_asv" python=3.9
        conda activate cloud_asv
        conda install asv
        conda list
    - name: Set up Asv
      run: |
        git fetch origin $GITHUB_BASE_REF:base $GITHUB_REF:incoming
        asv machine --machine github-cloud-machine --yes
    - name: asv continuous check
      run: asv continuous --only-changed -f 1.25 -v base incoming
