name: Benchmark with ASV

on:
  push:
    branches: asvDevBranch
  pull_request:
    branches: asvDevBranch

jobs:
  asvContinuous:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: conda-incubator/setup-miniconda@v3
      with:
        conda-build-version: 24.1.2
        activate-environment: cloud_env
        python-version: 3.9
    - name: Add conda to system path
      run: echo $CONDA/bin >> $GITHUB_PATH
    - name: Set up asv
      run: |
        conda install python=3.9
        conda install asv
        conda env list
        git fetch origin $GITHUB_BASE_REF:base $GITHUB_REF:incoming
        asv machine --machine github-cloud-machine --yes
    - name: asv continuous check
      run: asv continuous --only-changed -f 1.25 -v base incoming
