name: Benchmark with ASV

on:
  push:
    branches: asvDevBranch
  pull_request:
    branches: asvDevBranch # not tested yet

jobs:
  asvContinuous:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: conda-incubator/setup-miniconda@v3
      with:
        conda-version: 24.1.2
        activate-environment: cloud_env
        python-version: 3.12
    - name: Set up asv
      run: |
        conda install asv
        git fetch origin $GITHUB_BASE_REF:base $GITHUB_REF:incoming
        asv machine --machine github-cloud-machine --yes
    - name: asv continuous check
      run: asv continuous --only-changed -f 1.25 -v base incoming
