name: Benchmark with ASV

on:
  push:
    branches: asvDevBranch
  pull_request:
    branches: asvDevBranch

jobs:
  asvContinuous:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    - name: create environment.yml
      run: |
        conda install asv
    - name: Setup with asv
      run: |
        git fetch origin $GITHUB_BASE_REF:base $GITHUB_REF:pr
        asv machine --machine github-actions --yes
    - name: asv continuous check
      run: asv continuous -j 8 --only-changed -f 1.25 base pr
