name: black-check-latest
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Black version 19.10b0
        run:    pip install black==19.10b0
      - name: Run black --check --diff .
        run: black --check --diff .