name: Python Package using Conda

on: [push, workflow_dispatch]

jobs:
  build-all:
    name: scqubits testing (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            use-mamba: true
            auto-update-conda: true
            python-version: ${{ matrix.python-version }}
            channels: conda-forge
      - name: conda info
        run: conda info
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Lint with flake8
        run: |
          mamba install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Install all dependencies
        run: |
          mamba install --file ./requirements.txt -c conda-forge
          mamba install --file ./optional-requirements.txt -c conda-forge
          # The following is a temporary workaround for h5py hdf5 incompatibilities under conda install
          # conda remove h5py
          # pip install h5py
          pip install -e .
      - name: Attempt scqubits import
        run: python -c 'import scqubits'
      - name: Run all pytests (serial)
        run: |
          pytest -v --pyargs scqubits
      - name: Run all pytests (multiprocessing)
        run: |
          pytest -v --pyargs scqubits --num_cpus=4
